
version: "3.5"

services:
  db:
    image: "postgres:10"
    restart: 'always'
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "123456"
      POSTGRES_USER: "typeormcasino"
  
  adminer:
    image: "adminer"
    restart: "always"
    ports:
      - "8080:8080"